### ISSUE TITLE
Migrate to Iron

### ISSUE THREAD

**Issue by eeberhard** [aica-technology/docker-images#90]
```[tasklist]
### Tasks
- [ ] #86
- [ ] #88
- [ ] https://github.com/aica-technology/dynamic-components/issues/267
- [ ] aica-technology/modulo#32
- [ ] https://github.com/aica-technology/dynamic-state-engine/issues/117
```

**Comment by eeberhard** [comment]
@domire8 I think this one can also be closed 🔥
